In [1]:
# import required libraries
import numpy as np
import pandas as pd

In [10]:
# read dataset
dataset_url = "https://cdn-assets.theforage.com/vinternship_modules/kpmg_data_analytics/KPMG_VI_New_raw_data_update_final.xlsx"

transaction_df = pd.read_excel(dataset_url, sheet_name="Transactions", skiprows=1)
new_customer_list_df = pd.read_excel(
    dataset_url, sheet_name="NewCustomerList", skiprows=1
)
customer_demographic = pd.read_excel(
    dataset_url, sheet_name="CustomerDemographic", skiprows=1
)
customer_address = pd.read_excel(dataset_url, sheet_name="CustomerAddress", skiprows=1)

## Transaction worksheet

In [11]:
transaction_df.tail()

In [15]:
transaction_df.shape

(20000, 13)

In [16]:
transaction_df.dtypes

transaction_id                      int64
product_id                          int64
customer_id                         int64
transaction_date           datetime64[ns]
online_order                      float64
order_status                       object
brand                              object
product_line                       object
product_class                      object
product_size                       object
list_price                        float64
standard_cost                     float64
product_first_sold_date           float64
dtype: object

In [17]:
transaction_df.transaction_id.describe()

count    20000.000000
mean     10000.500000
std       5773.647028
min          1.000000
25%       5000.750000
50%      10000.500000
75%      15000.250000
max      20000.000000
Name: transaction_id, dtype: float64

In [18]:
transaction_df.product_id.describe()

count    20000.00000
mean        45.36465
std         30.75359
min          0.00000
25%         18.00000
50%         44.00000
75%         72.00000
max        100.00000
Name: product_id, dtype: float64

In [19]:
transaction_df.product_id.min()

0

In [20]:
transaction_df.customer_id.describe()

count    20000.000000
mean      1738.246050
std       1011.951046
min          1.000000
25%        857.750000
50%       1736.000000
75%       2613.000000
max       5034.000000
Name: customer_id, dtype: float64

In [26]:
transaction_df[
    ["brand", "product_line", "product_class", "product_size"]
].value_counts()

brand           product_line  product_class  product_size
Solex           Standard      medium         medium          2022
WeareA2B        Standard      medium         medium          1949
OHM Cycles      Standard      medium         medium          1079
Giant Bicycles  Standard      medium         medium           803
                                             large            770
Trek Bicycles   Standard      medium         large            673
Norco Bicycles  Standard      medium         medium           599
Giant Bicycles  Standard      high           medium           590
OHM Cycles      Standard      high           medium           576
Norco Bicycles  Road          medium         medium           513
Solex           Standard      medium         large            510
Norco Bicycles  Standard      low            medium           432
WeareA2B        Touring       medium         large            430
Solex           Standard      low            medium           410
WeareA2B        Standard      medium         small            397
Trek Bicycles   Road          medium         medium           397
OHM Cycles      Road          medium         medium           384
Giant Bicycles  Road          medium         medium           383
Norco Bicycles  Standard      medium         small            381
OHM Cycles      Standard      low            medium           380
Trek Bicycles   Standard      medium         small            378
Solex           Standard      high           medium           376
Trek Bicycles   Standard      high           medium           325
OHM Cycles      Touring       low            medium           229
Trek Bicycles   Road          medium         large            228
                Mountain      low            medium           223
Norco Bicycles  Road          medium         large            219
Solex           Touring       medium         large            208
Trek Bicycles   Standard      medium         medium           203
                Road          low            medium           201
OHM Cycles      Road          medium         small            200
Norco Bicycles  Mountain      low            small            200
Giant Bicycles  Road          low            small            196
                Standard      medium         small            196
OHM Cycles      Road          high           large            195
Giant Bicycles  Standard      high           small            195
Trek Bicycles   Standard      low            medium           193
Norco Bicycles  Standard      high           medium           192
                Road          high           large            191
Solex           Standard      high           large            190
WeareA2B        Touring       medium         medium           188
Solex           Road          medium         small            185
Norco Bicycles  Standard      high           small            183
Solex           Road          medium         large            183
Giant Bicycles  Touring       medium         large            179
WeareA2B        Standard      low            medium           174
Trek Bicycles   Road          low            small            169
Solex           Road          medium         medium           169
WeareA2B        Road          low            small            157
dtype: int64

In [27]:
transaction_df.list_price.describe()

count    20000.000000
mean      1107.829449
std        582.825242
min         12.010000
25%        575.270000
50%       1163.890000
75%       1635.300000
max       2091.470000
Name: list_price, dtype: float64

In [22]:
transaction_df.transaction_date.sort_values(
    ascending=True
), transaction_df.transaction_date.sort_values(ascending=False)

In [24]:
transaction_df.online_order.value_counts()

1.0    9829
0.0    9811
Name: online_order, dtype: int64

In [23]:
transaction_df.order_status.value_counts()

Approved     19821
Cancelled      179
Name: order_status, dtype: int64

In [28]:
transaction_df.standard_cost.describe()

count    19803.000000
mean       556.046951
std        405.955660
min          7.210000
25%        215.140000
50%        507.580000
75%        795.100000
max       1759.850000
Name: standard_cost, dtype: float64

## NewCustomerList worksheet

In [12]:
new_customer_list_df.tail()

In [30]:
new_customer_list_df.isna().sum()

first_name                               0
last_name                               29
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     17
job_title                              106
job_industry_category                  165
wealth_segment                           0
deceased_indicator                       0
owns_car                                 0
tenure                                   0
address                                  0
postcode                                 0
state                                    0
country                                  0
property_valuation                       0
Unnamed: 16                              0
Unnamed: 17                              0
Unnamed: 18                              0
Unnamed: 19                              0
Unnamed: 20                              0
Rank                                     0
Value                                    0
dtype: int64

In [31]:
new_customer_list_df.gender.value_counts()

Female    513
Male      470
U          17
Name: gender, dtype: int64

In [34]:
new_customer_list_df.past_3_years_bike_related_purchases.value_counts()

60    20
59    18
42    17
70    17
11    16
      ..
19     5
9      5
92     5
85     4
20     3
Name: past_3_years_bike_related_purchases, Length: 100, dtype: int64

In [35]:
new_customer_list_df.past_3_years_bike_related_purchases.dtypes

dtype('int64')

In [36]:
new_customer_list_df.DOB.sort_values()

In [37]:
new_customer_list_df.DOB.sort_values(ascending=False)

In [38]:
new_customer_list_df.job_industry_category.value_counts()

Financial Services    203
Manufacturing         199
Health                152
Retail                 78
Property               64
IT                     51
Entertainment          37
Argiculture            26
Telecommunications     25
Name: job_industry_category, dtype: int64

In [39]:
new_customer_list_df.wealth_segment.value_counts()

Mass Customer        508
High Net Worth       251
Affluent Customer    241
Name: wealth_segment, dtype: int64

In [40]:
new_customer_list_df.columns

Index(['first_name', 'last_name', 'gender',
       'past_3_years_bike_related_purchases', 'DOB', 'job_title',
       'job_industry_category', 'wealth_segment', 'deceased_indicator',
       'owns_car', 'tenure', 'address', 'postcode', 'state', 'country',
       'property_valuation', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Rank', 'Value'],
      dtype='object')

In [41]:
new_customer_list_df.owns_car.value_counts()

No     507
Yes    493
Name: owns_car, dtype: int64

In [42]:
new_customer_list_df.tenure

In [43]:
new_customer_list_df.postcode.describe()

count    1000.000000
mean     3019.227000
std       848.895767
min      2000.000000
25%      2209.000000
50%      2800.000000
75%      3845.500000
max      4879.000000
Name: postcode, dtype: float64

In [73]:
new_customer_list_df.state.value_counts()

NSW    506
VIC    266
QLD    228
Name: state, dtype: int64

In [50]:
new_customer_list_df.Rank.value_counts()

760     13
259     12
455      9
133      9
386      9
        ..
240      1
248      1
657      1
249      1
1000     1
Name: Rank, Length: 324, dtype: int64

In [48]:
new_customer_list_df.Rank.nunique()

324

In [53]:
new_customer_list_df.Value.describe()

count    1000.000000
mean        0.881714
std         0.293525
min         0.340000
25%         0.649531
50%         0.860000
75%         1.075000
max         1.718750
Name: Value, dtype: float64

## CustomerDemographic worksheet

In [13]:
customer_demographic.tail()

In [55]:
customer_demographic.columns

Index(['customer_id', 'first_name', 'last_name', 'gender',
       'past_3_years_bike_related_purchases', 'DOB', 'job_title',
       'job_industry_category', 'wealth_segment', 'deceased_indicator',
       'default', 'owns_car', 'tenure'],
      dtype='object')

In [56]:
customer_demographic.shape

(4000, 13)

In [57]:
customer_demographic.isna().sum()

customer_id                              0
first_name                               0
last_name                              125
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     87
job_title                              506
job_industry_category                  656
wealth_segment                           0
deceased_indicator                       0
default                                302
owns_car                                 0
tenure                                  87
dtype: int64

In [58]:
customer_demographic.dtypes

customer_id                                     int64
first_name                                     object
last_name                                      object
gender                                         object
past_3_years_bike_related_purchases             int64
DOB                                    datetime64[ns]
job_title                                      object
job_industry_category                          object
wealth_segment                                 object
deceased_indicator                             object
default                                        object
owns_car                                       object
tenure                                        float64
dtype: object

In [59]:
customer_demographic[["past_3_years_bike_related_purchases", "tenure"]].describe()

       past_3_years_bike_related_purchases       tenure
count                          4000.000000  3913.000000
mean                             48.890000    10.657041
std                              28.715005     5.660146
min                               0.000000     1.000000
25%                              24.000000     6.000000
50%                              48.000000    11.000000
75%                              73.000000    15.000000
max                              99.000000    22.000000

In [60]:
customer_demographic.gender.value_counts()

Female    2037
Male      1872
U           88
F            1
Femal        1
M            1
Name: gender, dtype: int64

In [61]:
customer_demographic.DOB.sort_values()

In [62]:
customer_demographic.DOB.sort_values(ascending=False)

In [63]:
customer_demographic.job_industry_category.value_counts()

Manufacturing         799
Financial Services    774
Health                602
Retail                358
Property              267
IT                    223
Entertainment         136
Argiculture           113
Telecommunications     72
Name: job_industry_category, dtype: int64

In [64]:
customer_demographic.wealth_segment.value_counts()

Mass Customer        2000
High Net Worth       1021
Affluent Customer     979
Name: wealth_segment, dtype: int64

In [65]:
customer_demographic.deceased_indicator.value_counts()

N    3998
Y       2
Name: deceased_indicator, dtype: int64

In [66]:
customer_demographic.default.value_counts()

100                                       113
1                                         112
-1                                        111
-100                                       99
Ù¡Ù¢Ù£                                     53
                                         ...
testâ testâ«                               31
/dev/null; touch /tmp/blns.fail ; echo     30
âªâªtestâª                                 29
ì¸ëë°í ë¥´                                 27
,ãã»:*:ã»ãâ( â» Ï â» )ãã»:*:ã»ãâ           25
Name: default, Length: 90, dtype: int64

In [67]:
customer_demographic.owns_car.value_counts()

Yes    2024
No     1976
Name: owns_car, dtype: int64

## CustomerAddress worksheet

In [14]:
customer_address.tail()

In [68]:
customer_address.shape

(3999, 6)

In [69]:
customer_address.dtypes

customer_id            int64
address               object
postcode               int64
state                 object
country               object
property_valuation     int64
dtype: object

In [70]:
customer_address[["customer_id", "postcode", "property_valuation"]].describe()

       customer_id     postcode  property_valuation
count  3999.000000  3999.000000         3999.000000
mean   2003.987997  2985.755939            7.514379
std    1154.576912   844.878364            2.824663
min       1.000000  2000.000000            1.000000
25%    1004.500000  2200.000000            6.000000
50%    2004.000000  2768.000000            8.000000
75%    3003.500000  3750.000000           10.000000
max    4003.000000  4883.000000           12.000000

In [71]:
customer_address.isna().sum()

customer_id           0
address               0
postcode              0
state                 0
country               0
property_valuation    0
dtype: int64

In [72]:
customer_address.state.value_counts()

NSW                2054
VIC                 939
QLD                 838
New South Wales      86
Victoria             82
Name: state, dtype: int64

In [74]:
customer_address.country.value_counts()

Australia    3999
Name: country, dtype: int64